version: '3.8'

services:
    php:
        build:
            context: .
            dockerfile: Dockerfile
        image: alineck09/telegram-bot:php-latest

        volumes:
            - .:/app
        expose:
            - "9000"

        networks:
            - app-network

        depends_on:
          - postgresql

    nginx:
        build:
            context: ./nginx
            dockerfile: Dockerfile
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/html
        depends_on:
            - php

        networks:
            - app-network

    postgresql:
        container_name: postgres

        image: postgres:16-alpine

        environment:
            POSTGRES_USER: ${DB_USERNAME:-postgres}
            POSTGRES_PASSWORD: ${DB_PASSWORD:-defaultpassword}
            PG_DATA: /var/lib/postgresql/data

        volumes:
            - ./data:/var/lib/postgresql/data
            - ./logs:/var/log/postgresql
            - ./postgresql.conf:/etc/postgresql/postgresql.conf
            - ./pg_hba.conf:/etc/postgresql/pg_hba.conf

        command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf",
        "-c", "hba_file=/etc/postgresql/pg_hba.conf"]

        ports:
            - "5432:5432"

volumes:
    data:
        driver: local
    logs:
        driver: local

networks:
    app-network:
        driver: bridge



