version: '3.8'

services:
    php:
        build:
            context: .
            dockerfile: Dockerfile
        image: alineck09/telegram-bot:php-latest
        network_mode: host
        env_file:
            - .env.production
        volumes:
            - .:/app
        expose:
            - "9000"

    nginx:
        build:
            context: ./nginx
            dockerfile: Dockerfile
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/html
        depends_on:
            - php
        network_mode: host


