version: '3.8'

services:
    php:
        build:
            context: .
            dockerfile: Dockerfile
        image: alineck09/telegram-bot:php-latest
        environment:
            - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
        volumes:
            - .:/app
        expose:
            - "9000"
        networks:
            - app-network

    nginx:
        build:
            context: ./nginx
            dockerfile: Dockerfile
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/html
        depends_on:
            - php
        networks:
            - app-network

    postgresql:
        image: postgres:14-alpine
        environment:
            DB_CONNECTION: ${DB_SECOND_CONNECTION}
            DB_HOST: ${DB_SECOND_HOST}
            DB_PORT: ${DB_SECOND_PORT}
            DB_USERNAME: ${DB_SECOND_USERNAME}
            DB_DATABASE: ${DB_SECOND_DATABASE}
            DB_PASSWORD: ${DB_SECOND_PASSWORD}
        volumes:
            - db:/var/lib/postgresql/data
        networks:
           - app-network

networks:
    app-network:
        driver: bridge

