name: CI

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

#      - name: Activation PostgresSQL
#        run: |
#          for i in {1..10}; do
#           nc -zv ${{ secrets.DB_HOST }} 5432 && break
#           echo "Waiting for PostgreSQL..."
#           sleep 3
#          done
#      - name: Migration
#        run: |
#          DB_USERNAME=${{ secrets.DB_USERNAME }}
#          DB_PASSWORD=${{ secrets.DB_PASSWORD }}
#          DB_DATABASE=${{ secrets.DB_DATABASE }}
#          php artisan migrate --force

      - name: Set up SSH and deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            cd warship-game
            echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login --username "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin
            docker exec telegram-bot_php php artisan migrate --force
            ./deploy.sh
