name: CI

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build Docker Images
        run: |
            docker build --platform linux/amd64 -t "alineck09/telegram-bot:php-latest-${{ github.sha }}" -f Dockerfile .
            docker build --platform linux/amd64 -t "alineck09/telegram-bot:nginx-latest-${{ github.sha }}" -f nginx/Dockerfile ./nginx/

      - name: Tag and Push 'latest' versions
        run: |
            docker tag "alineck09/telegram-bot:php-latest-${{ github.sha }}" "alineck09/telegram-bot:php-latest"
            docker tag "alineck09/telegram-bot:nginx-latest-${{ github.sha }}" "alineck09/telegram-bot:nginx-latest"
            docker push "alineck09/telegram-bot:php-latest"
            docker push "alineck09/telegram-bot:nginx-latest"

      - name: Set up SSH and deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            cd warship-game
            echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login --username "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

            ./deploy.sh

