name: CI

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login --username "alineck09" --password-stdin

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Images
        run: |
          docker buildx build --platform linux/amd64 -t "alineck09/telegram-bot:php-latest-${{ github.sha }}" -f Dockerfile .
          docker buildx build --platform linux/amd64 -t "alineck09/telegram-bot:nginx-latest-${{ github.sha }}" -f nginx/Dockerfile ./nginx/

      - name: Docker Push Images
        run: |
          docker push "alineck09/telegram-bot:php-latest-${{ github.sha }}"
          docker push "alineck09/telegram-bot:nginx-latest-${{ github.sha }}"

      - name: Tag and Push 'latest' versions
        run: |
          docker tag "${{ secrets.DOCKER_HUB_USERNAME }}/telegram-bot:php-latest-${{ github.sha }}" "alineck09/telegram-bot:php-latest"
          docker tag "${{ secrets.DOCKER_HUB_USERNAME }}/telegram-bot:nginx-latest-${{ github.sha }}" "alineck09/telegram-bot:nginx-latest"
          docker push "alineck09/telegram-bot:php-latest"
          docker push "alineck09/telegram-bot:nginx-latest"

      - name: Deploy to Linux server
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.SERVER_IP}}
          username: ${{ secrets.SSH_USER}}
          key: ${{ secrets.SSH_PRIVATE_KEY}}
          scripts: |
            cd /telegram-bot
            ./deploy.sh
