name: CI

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo ${{ secrets.DOCKER_HUB_PASSWORD }} | docker login --username ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin

      - name: Build Docker Images
        run: |
            TAG_PHP="${{ secrets.DOCKER_HUB_USERNAME }}/telegram-bot:php-latest-${{ github.sha }}"
            TAG_NGINX="${{ secrets.DOCKER_HUB_USERNAME }}/telegram-bot:nginx-latest-${{ github.sha }}"
            echo "Building PHP image with tag: $TAG_PHP"
            docker build -t "$TAG_PHP" -f Dockerfile .
            echo "Building Nginx image with tag: $TAG_NGINX"
            docker build -t "$TAG_NGINX" -f nginx/Dockerfile ./nginx

      - name: Push Docker Images
        run: |
            TAG_PHP="${{ secrets.DOCKER_HUB_USERNAME }}/telegram-bot:php-latest-${{ github.sha }}"
            TAG_NGINX="${{ secrets.DOCKER_HUB_USERNAME }}/telegram-bot:nginx-latest-${{ github.sha }}"
            docker push "$TAG_PHP"
            docker push "$TAG_NGINX"

      - name: Tag and Push 'latest' Versions
        run: |
            TAG_PHP="${{ secrets.DOCKER_HUB_USERNAME }}/telegram-bot:php-latest-${{ github.sha }}"
            TAG_NGINX="${{ secrets.DOCKER_HUB_USERNAME }}/telegram-bot:nginx-latest-${{ github.sha }}"
            docker tag "$TAG_PHP" "${{ secrets.DOCKER_HUB_USERNAME }}/telegram-bot:php-latest"
            docker tag "$TAG_NGINX" "${{ secrets.DOCKER_HUB_USERNAME }}/telegram-bot:nginx-latest"
            docker push "${{ secrets.DOCKER_HUB_USERNAME }}/telegram-bot:php-latest"
            docker push "${{ secrets.DOCKER_HUB_USERNAME }}/telegram-bot:nginx-latest"

      - name: Deploy to Linux server
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.SERVER_IP}}
          username: ${{ secrets.SSH_USER}}
          key: ${{secrets.SSH_PRIVATE_KEY}}
          scripts: |
            cd /telegram-bot/deploy.sh
            ./deploy.sh
